spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/datajpa
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: zerobase
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        #        show_sql: true
logging:
  level:
    org.hibernate.sql : debug
