spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/datajpa
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: zerobase

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.sql : debug
    #JPA 가 실행하는 쿼리를 로그에 남김
